site_name: exoatlas
site_url: https://zkbt.github.com/exoatlas
nav:
    - index.md
    - installation.ipynb
    - quickstart.ipynb
    - User Guide:
      - populations.ipynb
      - creating.ipynb
      - curating.ipynb
      - filtering.ipynb
      - visualizing.ipynb
      - uncertainties.ipynb
    - Developer Guide:
      - github.ipynb
      - testing.ipynb
      - documentation.ipynb
    - Details:
      - compare-nasa-exoplanet-archive-tables.ipynb
theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/exoatlas/
plugins:
  - search
  - mkdocs-jupyter:
      execute : True
      include_source : True
  - exclude:
      glob:     
        - "downloads-for-exoatlas/*"
        - "*.pdf"
        - "*.fits"
        - "*.npy"
        - "*.ecsv"
markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
